platform :macos, '10.13'
use_frameworks!

def common
  pod 'GRDB.swift/SQLCipher', path: '../../..'
  pod 'SQLCipher', '~> 4.0', inhibit_warnings: true
end

target 'GRDBTests' do
  common
end

target 'GRDBTestsEncrypted' do
  common
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Workaround for Xcode 14.3+
      # https://github.com/CocoaPods/CocoaPods/issues/11839
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.13'
      config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '3'
    end
  end
end
