use_frameworks!
target 'iOS'
platform :ios, '9.0'
supports_swift_versions '4.2'
pod 'GRDB.swift', :path => '../../..'

post_install do |installer|
  installer.pods_project.targets.select { |target| target.name == "GRDB.swift" }.each do |target|
    target.build_configurations.each do |config|
      # Enable extra GRDB APIs
      config.build_settings['OTHER_SWIFT_FLAGS'] = "$(inherited) -D SQLITE_ENABLE_FTS5 -D SQLITE_ENABLE_PREUPDATE_HOOK"
      # Enable extra SQLite APIs
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = "$(inherited) GRDB_SQLITE_ENABLE_PREUPDATE_HOOK=1"
    end
  end
end
