platform :macos, '10.13'
use_frameworks!

def common
  pod 'GRDB.swift/SQLCipher', path: '../../..'
  pod 'SQLCipher', '~> 3.0', inhibit_warnings: true
end

target 'GRDBTests' do
  common
end

target 'GRDBTestsEncrypted' do
  common
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Workaround for Xcode 14.3+
      # https://github.com/CocoaPods/CocoaPods/issues/11839
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.13'
      config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '3'
    end
  end

  # TODO: remove when https://github.com/CocoaPods/CocoaPods/pull/12009 is merged.
  # https://github.com/CocoaPods/CocoaPods/issues/12012#issuecomment-1655191516
  installer.aggregate_targets.each do |target|
    target.xcconfigs.each do |variant, xcconfig|
      xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)
      IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
    end
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
        xcconfig_path = config.base_configuration_reference.real_path
        IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
      end
    end
  end
end
